<a href="https://colab.research.google.com/github/dude123studios/AdvancedDeepLearning/blob/main/GPU_Distribution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np
from tensorflow import keras

N_TRAIN_EXAMPLES = 2**20
N_FEATURES = 10
BATCH_SIZE = 256

x = np.random.random((N_TRAIN_EXAMPLES,N_FEATURES))
y = np.random.randint(2,size=(N_TRAIN_EXAMPLES,1))
x = tf.dtypes.cast(x,tf.float32)
print(x)
print('\n')
print(y)

tf.Tensor(
[[0.4582237  0.72583795 0.199992   ... 0.38261086 0.65051234 0.28819433]
 [0.7527232  0.6197965  0.9709689  ... 0.10873412 0.28183696 0.9362707 ]
 [0.4967143  0.649683   0.00583366 ... 0.02706137 0.05541427 0.77816194]
 ...
 [0.7303165  0.7786472  0.32133842 ... 0.20499389 0.5383262  0.4262376 ]
 [0.05156194 0.90937054 0.11157741 ... 0.87956405 0.49459043 0.604477  ]
 [0.31527063 0.75491154 0.7741476  ... 0.13744509 0.59142286 0.76089656]], shape=(1048576, 10), dtype=float32)


[[1]
 [0]
 [0]
 ...
 [0]
 [0]
 [1]]


In [ ]:
dataset = tf.data.Dataset.from_tensor_slices((x,y))
dataset = dataset.shuffle(buffer_size=N_TRAIN_EXAMPLES).batch(BATCH_SIZE)

distribution = tf.distribute.MirroredStrategy()

with distribution.scope():
    model = keras.Sequential()
    model.add(keras.layers.Dense(16,activation='relu',input_shape=(N_FEATURES,)))
    model.add(keras.layers.Dense(1,activation='sigmoid'))
    optimizer = tf.keras.optimizers.SGD(0.2)
    model.compile(loss='binary_crossentropy',optimizer=optimizer)
    
model.summary()
model.fit(dataset,epochs=5,steps_per_epoch=10)



INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 16)                176       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                